replace var1="AU" if var1=="Australia"
replace var1="AT" if var1=="Austria"
replace var1="BE" if var1=="Belgium"
replace var1="CAN" if var1=="Canada"
replace var1="CHI" if var1=="Chile"
replace var1="CZE" if var1=="Czech Republic"
replace var1="DK" if var1=="Denmark"
replace var1="EE" if var1=="Estonia"
replace var1="FI" if var1=="Finland"
replace var1="FR" if var1=="France"
replace var1="DE" if var1=="Germany"
replace var1="GR" if var1=="Greece"
replace var1="HU" if var1=="Hungary"
replace var1="ICE" if var1=="Iceland"
replace var1="IE" if var1=="Ireland"
replace var1="IS" if var1=="Israel*"
replace var1="IT" if var1=="Italy"
replace var1="JP" if var1=="Japan"
replace var1="KO" if var1=="Korea"
replace var1="LU" if var1=="Luxembourg"
replace var1="NL" if var1=="Netherlands"
replace var1="NZ" if var1=="New Zealand"
replace var1="NO" if var1=="Norway"
replace var1="PL" if var1=="Poland"
replace var1="PT" if var1=="Portugal"
replace var1="SK" if var1=="Slovak Republic"
replace var1="SI" if var1=="Slovenia"
replace var1="ES" if var1=="Spain"
replace var1="SE" if var1=="Sweden"
replace var1="CH" if var1=="Switzerland"
replace var1="TR" if var1=="Turkey**"
replace var1="UK" if var1=="United Kingdom"
replace var1="US" if var1=="United States"
replace var1="BG" if var1=="Bulgaria"
replace var1="CY" if var1=="Cyprus†"
replace var1="LT" if var1=="Latvia"
replace var1="LV" if var1=="Lithuania"
replace var1="MT" if var1=="Malta"
replace var1="RO" if var1=="Romania"
replace var1="OECD" if var1=="OECD Median"
replace var1="EU" if var1=="EU Median"
replace var1="AEU" if var1=="Additional EU Countries"


